"""Constants file."""

# A list of songwriters with articles on wikipedia
LIST_OF_SONGWRITERS = [
    'Lisandro Abadie',
    'Miguel Abuelo',
    'Carlos Acuña',
    'King África',
    'Oscar Alemán',
    'Marcelo Álvarez',
    'Benjamin Amadeo',
    'Mike Amigorena',
    'Carlos De Antonis',
    'Lisandro Aristimuño',
    'Federico Aubele',
    'Axel',
    'Pedro Aznar',
    'Bahiano',
    'Juan Carlos Baglietto',
    'Abel Balbo',
    'Adrián Barilari',
    'Dimi Bass',
    'Daniela Anahi Bessia',
    'Claudio Basso',
    'Alfredo Belusi',
    'Patricio Borghetti',
    'Germán Burgos',
    'Manuel Buzón',
    'Facundo Cabral',
    'Jorge Cafrune',
    'Andrés Calamaro',
    'Carlos Casella',
    'Gustavo Cerati',
    'Tito Climent',
    'Alberto Cortez',
    'Sandro de América',
    'Jimena Fama',
    'Dora Gález',
    'Charly García',
    'Carlos Gardel',
    'León Gieco',
    'Gilda',
    'Horacio Guarany',
    'Gloria Guzmán',
    'Víctor Heredia',
    'Alejandro Lerner',
    'Luisana Lopilato',
    'Valeria Lynch',
    'Robby Maria',
    'Juanita Martínez',
    'Lucas Masciano',
    'Sandra Mihanovich',
    'Amelia Mirel',
    'Ricardo Mollo',
    'Lely Morel',
    'Marcela Morelo',
    'Adrián Otero',
    'Fito Páez',
    'Soledad Pastorutti',
    'Luciano Pereyra',
    'Abel Pintos',
    'Luciana Salazar',
    'Noel Schajris',
    'Patricia Sosa',
    'Luis Alberto Spinetta',
    'Martina Stoessel',
    'Tanguito',
    'Diego Torres',
    'Bren Vaneske',
    'María Elena Walsh',
    'Atahualpa Yupanqui',
    'Miguel Zavaleta',
    'Peter Allen',
    'Tina Arena',
    'Jimmy Barnes',
    'Sarah Blasko',
    'Eric Bogle',
    'Daryl Braithwaite',
    'Rose Bygrave',
    'Kev Carmody',
    'Cletis Carr',
    'Nick Cave',
    'Ned Collette',
    'Ricki-Lee Coulter',
    'Paul Dempsey',
    'Johnny Diesel',
    'Joe Dolce',
    'Slim Dusty',
    'Bernard Fanning',
    'John Farnham',
    'Bobby Flynn',
    'Robert Forster',
    'Tim Freedman',
    'Sia Furler',
    'Delta Goodrem',
    'Darren Hayes',
    'Missy Higgins',
    'Jarryd James',
    'Paul Kelly',
    'Ben Lee',
    'Lior',
    'Alex Lloyd',
    'Robyn Loau',
    'Jessica Mauboy',
    'David McComb',
    'Hugh McDonald',
    'Andrea McEwan',
    'Grant McLennan',
    'Lisa Miller',
    'Kate Miller-Heidke',
    'Tim Minchin',
    'Lisa Mitchell',
    'Pete Murray',
    'Olivia Newton-John',
    'Kevin Parker',
    'Paulini',
    'Josh Pyke',
    'James Reyne',
    'Tim Rogers',
    'Xavier Rudd',
    'Saritah',
    'Guy Sebastian',
    'Mark Seymour',
    'Troye Sivan',
    'Rob Swire',
    'Billy Thorpe',
    'Holly Throsby',
    'Megan Washington',
    'Darlene Zschech',
    'Wolfgang Ambros',
    'Peter Cornelius',
    'Georg Danzer',
    'Rainhard Fendrich',
    'Sissy Handler',
    'André Heller',
    'Michael Heltau',
    'Udo Jürgens',
    'Robby Maria',
    'Anja Plaschg',
    'Willi Resetarits',
    'Alison Hinds',
    'Rihanna',
    'Rupee',
    'Shontelle',
    'Sarah Bettens',
    'Jacques Brel',
    'Ozark Henry',
    'Lara Fabian',
    'Flip Kowlier',
    'Milow',
    'Selah Sue',
    'Stromae',
    'Kemal Monteno',
    'Jorge Ben',
    'Chico Buarque',
    'Alice Caymmi',
    'Roberto Carlos',
    'Fagner',
    'Ludmila Ferber',
    'Paula Fernandes',
    'Gilberto Gil',
    'João Gilberto',
    'Antônio Carlos Jobim',
    'Tom Jobim',
    'Vinicius de Moraes',
    'Ana Nóbrega',
    'Zé Ramalho',
    'Gabriela Rocha',
    'Angela Ro Ro',
    'Israel Salazar',
    'Nívea Soares',
    'Juliano Son',
    'Ana Paula Valadão',
    'André Valadão',
    'Caetano Veloso',
    'Xuxa',
    'Pan Ron',
    'Ros Serey Sothea',
    'Sinn Sisamouth',
    'Bryan Adams',
    'Jugpreet Singh Bajwa',
    'Susan Aglukark',
    'Paul Anka',
    'Jann Arden',
    'Tal Bachman',
    'Victoria Banks',
    'Jill Barber',
    'Daniel Bélanger',
    'Willie P. Bennett',
    'Moe Berg',
    'Art Bergmann',
    'Justin Bieber',
    'Bif Naked',
    'David Bradstreet',
    'Dean Brody',
    'Jim Bryson',
    'Basia Bulat',
    'Meryn Cadell',
    'Alessia Cara',
    'Craig Cardiff',
    'Andrew Cash',
    'Alanna Clarke',
    'Tom Cochrane',
    'Bruce Cockburn',
    'Leonard Cohen',
    'Holly Cole',
    'Jason Collett',
    'Stompin\' Tom Connors',
    'J.P. Cormier',
    'Rose Cousins',
    'Allison Crowe',
    'Lori Cullen',
    'Amelia Curran',
    'Rick Danko',
    'Mac Demarco',
    'Celine Dion',
    'Melanie Doane',
    'Bonnie Dobson',
    'Fefe Dobson',
    'Julie Doiron',
    'Luke Doucet',
    'Alan Doyle',
    'Damhnait Doyle',
    'Drake',
    'Fred J. Eaglesmith',
    'Kathleen Edwards',
    'Lara Fabian',
    'Stephen Fearing',
    'Leslie Feist',
    'Christine Fellows',
    'Ferron',
    'Jeremy Fisher',
    'David Francey',
    'Nelly Furtado',
    'Garou',
    'Joel Gibb',
    'Ariana Gillis',
    'Matthew Good',
    'Sebastien Grainger',
    'Jenn Grant',
    'Dallas Green',
    'Jack Grunsky',
    'Emm Gryner',
    'Emily Haines',
    'Sarah Harmer',
    'Hayden',
    'Rob Heath',
    'Dan Hill',
    'Veda Hille',
    'Terry Jacks',
    'Colin James',
    'Carly Rae Jepsen',
    'Steve Jocz',
    'Alexz Johnson',
    'Sass Jordan',
    'Connie Kaldor',
    'James Keelaghan',
    'Chantal Kreviazuk',
    'k.d. lang',
    'Plume Latraverse',
    'Lisa Lavie',
    'Avril Lavigne',
    'Daniel Lavoie',
    'Félix Leclerc',
    'Jean Leloup',
    'Gordon Lightfoot',
    'Lights',
    'Corb Lund',
    'Tara MacLean',
    'Catherine MacLellan',
    'Dan Mangan',
    'Richard Manuel',
    'Amanda Marshall',
    'Melissa McClelland',
    'Eileen McGann',
    'Kate & Anna McGarrigle',
    'Loreena McKennitt',
    'Sarah McLachlan',
    'Holly McNarland',
    'Shawn Mendes',
    'Lynn Miles',
    'Amy Millan',
    'Joni Mitchell',
    'Ruth Moody',
    'Alanis Morissette',
    'Emilie Mover',
    'Sierra Noble',
    'Mary Margaret O\'Hara',
    'Old Man Luedecke',
    'Maren Ord',
    'Blair Packham',
    'Chris Patrick',
    'Carole Pope',
    'Jan Randall',
    'Jimmy Rankin',
    'Michel Rivard',
    'Sam Roberts',
    'Garnet Rogers',
    'Stan Rogers',
    'Louis Royer',
    'Buffy Sainte-Marie',
    'John K. Samson',
    'Drew Seeley',
    'Lorraine Segato',
    'Jay Semko',
    'Ron Sexsmith',
    'Jane Siberry',
    'R. Dean Taylor',
    'Tegan and Sara',
    'Shania Twain',
    'Ian Tyson',
    'Sylvia Tyson',
    'Martha Wainwright',
    'Rufus Wainwright',
    'Patrick Watson',
    'David Wiffen',
    'Hawksley Workman',
    'Neil Young',
    'Brigitte Zarie',
    'Joel Zifkin',
    'Beto Cuevas',
    'Gepe',
    'Víctor Jara',
    'Javiera Mena',
    'Ángel Parra',
    'Javiera Parra',
    'Nicanor Parra',
    'Violeta Parra',
    'Alci Acosta',
    'Albalucía Ángel',
    'Lucas Arnau',
    'J Balvin',
    'Naty Botero',
    'Cabas',
    'Alex Campos',
    'Jorge Celedón',
    'Andrés Cepeda',
    'ChocQuibTown',
    'Silvestre Dangond',
    'Margarita Rosa de Francisco',
    'Diomedes Díaz',
    'Alejo Durán',
    'Andrea Echeverri',
    'Juan Carlos Echeverry',
    'Estéfano',
    'Fatiniza',
    'Fonseca',
    'Darío Gómez',
    'Marta Gómez',
    'Leonor Gonzalez Mina',
    'Ivonne Guzmán',
    'Carolina Herrera',
    'Illona',
    'Juanes',
    'Totó la Momposina',
    'Carolina la O',
    'Fanny Lú',
    'Maía',
    'Maluma',
    'Marbelle',
    'Marce',
    'Andrés Mercado',
    'Ericson Alexander Molano',
    'Jorge Oñate',
    'Elkin Ramírez',
    'Valentina Rendón',
    'Reykon',
    'Jery Sandoval',
    'Shakira',
    'Soraya',
    'Ali Stone',
    'Andrés Useche',
    'Jorge Villamizar',
    'Iván Villazón',
    'Carlos Vives',
    'Charlie Zaa',
    'Emiliano Zuleta',
    'Arsen Dedić',
    'Oliver Dragojević',
    'Albita',
    'Camila Cabello',
    'Osmani García',
    'Pablo Milanés',
    'Silvio Rodríguez',
    'Jaroslav Hutka',
    'Tomáš Klus',
    'Karel Kryl',
    'Vladimír Merta',
    'Jaromír Nohavica',
    'Karel Plíhal',
    'Vlastimil Třešňák',
    'Xindl X',
    'Alberte',
    'Tim Christensen',
    'Anna David',
    'King Diamond',
    'Tina Dickow',
    'Thomas Helmig',
    'Mads Langer',
    'Kim Larsen',
    'MØ',
    'Rasmus Nøhr',
    'Agnes Obel',
    'Sebastian',
    'Anaís',
    'Charytín',
    'Juan Luis Guerra',
    'Sandra Zaiter',
    'Moustafa Amar',
    'Angham',
    'Amr Diab',
    'Mohammad Fouad',
    'Mohamed Hamaki',
    'Tamer Hosny',
    'Amal Maher',
    'Hani Shaker',
    'Sherine',
    'Carmen Suleiman',
    'Álvaro Torres',
    'Eivør',
    'Guðrið Hansdóttir',
    'Teitur Lassen',
    'Ismo Alanko',
    'Chisu',
    'Jippu',
    'J. Karjalainen',
    'Anssi Kela',
    'Mikko Kuustonen',
    'Juice Leskinen',
    'Jarkko Martikainen',
    'Jonna Tervomaa',
    'Maija Vilkkumaa',
    'Dominique A',
    'Charles Aznavour',
    'Barbara',
    'Georges Brassens',
    'Carla Bruni',
    'Francis Cabrel',
    'Camille',
    'Louis Chedid',
    'Yves Duteil',
    'Mylène Farmer',
    'Jean Ferrat',
    'Léo Ferré',
    'Nino Ferrer',
    'Thomas Fersen',
    'Serge Gainsbourg',
    'Jean-Jacques Goldman',
    'Jacques Higelin',
    'Alexis HK',
    'Juliette',
    'Bernard Lavilliers',
    'Nolwenn Leroy',
    'Albert Marcœur',
    'Nina Morato',
    'Georges Moustaki',
    'Claude Nougaro',
    'Pierre Perret',
    'Michel Polnareff',
    'Renaud',
    'Véronique Sanson',
    'Mano Solo',
    'Alain Souchon',
    'Boris Vian',
    'Laurent Voulzy',
    'Katie Melua',
    'Ayọ',
    'Wolf Biermann',
    'Clemens Bittlinger',
    'Clueso',
    'Funny van Dannen',
    'Franz Josef Degenhardt',
    'Dota',
    'Siegfried Fietz',
    'Herbert Grönemeyer',
    'Klaus Hoffmann',
    'Hanns Dieter Hüsch',
    'Gisbert zu Knyphausen',
    'Udo Lindenberg',
    'Peter Maffay',
    'Reinhard Mey',
    'Marius Müller-Westernhagen',
    'Julia Neigel',
    'Martin Gotthard Schneider',
    'Olli Schulz',
    'Manfred Siebald',
    'Hannes Wader',
    'Konstantin Wecker',
    'Johanna Zeul',
    'Joana Zimmer',
    'Haris Alexiou',
    'Andriana Babali',
    'George Dalaras',
    'Michalis Hatzigiannis',
    'Lavrentis Machairitsas',
    'Vasilis Papakonstantinou',
    'Demis Roussos',
    'Ricardo Arjona',
    'Gaby Moreno',
    'Shery',
    'Vera Schmidt',
    'Ólöf Arnalds',
    'Ásgeir Trausti',
    'Björk',
    'Jónsi',
    'Lay Low',
    'Megas',
    'Emilíana Torrini',
    'Svavar Knútur',
    'Talat Aziz',
    'Badshah',
    'Jugpreet Singh Bajwa',
    'S. P. Balasubrahmanyam',
    'Rekha Bhardwaj',
    'Vishal Bhardwaj',
    'Dilpreet Bhatia',
    'Asha Bhonsle',
    'Sunidhi Chauhan',
    'Alisha Chinai',
    'Vishal Dadlani',
    'Manna Dey',
    'Zubeen Garg',
    'Shreya Ghoshal',
    'Gippy Grewal',
    'Hariharan',
    'Ilaiyaraaja',
    'Mahalaxmi Iyer',
    'Neha Kakkar',
    'Suman Kalyanpur',
    'Hard Kaur',
    'Harshdeep Kaur',
    'Kishor Kumar',
    'Babbu Maan',
    'Shankar Mahadevan',
    'Anushka Manchanda',
    'Lata Mangeshkar',
    'Talat Mehmood',
    'Salim Merchant',
    'Palak Muchhal',
    'Mukesh',
    'Udit Narayan',
    'Sonu Nigam',
    'Damodar Raao',
    'Mohammad Rafi',
    'A. R. Rahman',
    'Anirudh Ravichander',
    'Himesh Reshammiya',
    'Anupam Roy',
    'Kumar Sanu',
    'Shaan',
    'Arijit Singh',
    'Honey Singh',
    'Jagjit Singh',
    'Sukhwinder Singh',
    'Kavita Subramaniam',
    'Pankaj Udhas',
    'Usha Uthup',
    'Suresh Wadkar',
    'Alka Yagnik',
    'K. J. Yesudas',
    'Ebiet G Ade',
    'Maudy Ayunda',
    'Iwan Fals',
    'Fariz RM',
    'Melly Goeslaw',
    'Gombloh',
    'Harry Roesli',
    'Sandhy Sondoro',
    'Yockie Suryoprayogo',
    'Shadmehr Aghili',
    'Faramarz Aslani',
    'Mohammad Esfahani',
    'Shahyar Ghanbari',
    'Hichkas',
    'Shahram Nazeri',
    'Mohammad Reza Shajarian',
    'Reza Yazdani',
    'Mohsen Yeganeh',
    'Luka Bloom',
    'Bono',
    'Paul Brady',
    'Paddy Casey',
    'Mic Christopher',
    'Andrea Corr',
    'Sharon Corr',
    'Damien Dempsey',
    'Janet Devlin',
    'EDEN',
    'Mick Flannery',
    'Dave Flynn',
    'Mark Geary',
    'Lisa Hannigan',
    'Glen Hansard',
    'Frank Harte',
    'Gemma Hayes',
    'Margaret Healy',
    'Christie Hennessy',
    'David Hopkins',
    'Niall Horan',
    'Hozier',
    'Andy Irvine',
    'Katie Kim',
    'Vyvienne Long',
    'Phil Lynott',
    'Shane MacGowan',
    'James Vincent McMorrow',
    'Christy Moore',
    'Van Morrison',
    'Johnny Moynihan',
    'Mundy',
    'Sinéad O\'Connor',
    'Ted O\'Neill',
    'Declan O\'Rourke',
    'Fionn Regan',
    'Damien Rice',
    'Ann Scott',
    'Chris Singleton',
    'Emmett Tinley',
    'Andy White',
    'Chava Alberstein',
    'Meir Ariel',
    'Shlomo Artzi',
    'Izhar Ashdot',
    'Ehud Banai',
    'David Broza',
    'Matti Caspi',
    'Ilan Chester',
    'Arik Einstein',
    'Aviv Geffen',
    'Shlomo Gronich',
    'Shalom Hanoch',
    'Dana International',
    'Achinoam Nini',
    'Idan Raichel',
    'Naomi Shemer',
    'Harel Skaat',
    'Ariel Zilber',
    'Alice',
    'Biagio Antonacci',
    'Claudio Baglioni',
    'Franco Battiato',
    'Lucio Battisti',
    'Edoardo Bennato',
    'Samuele Bersani',
    'Andrea Bocelli',
    'Angelo Branduardi',
    'Marianna Cataldi',
    'Adriano Celentano',
    'Chiara Civello',
    'Riccardo Cocciante',
    'Carmen Consoli',
    'Cesare Cremonini',
    'Lucio Dalla',
    'Pino Daniele',
    'Fabrizio De André',
    'Francesco De Gregori',
    'Dolcenera',
    'Elisa',
    'Sergio Endrigo',
    'Tiziano Ferro',
    'Gabriella Ferri',
    'Zucchero Fornaciari',
    'Ivano Fossati',
    'Giorgio Gaber',
    'Francesco Guccini',
    'Jovanotti',
    'Luciano Ligabue',
    'Nada',
    'Gianna Nannini',
    'Domenico Modugno',
    'Gianni Morandi',
    'Gino Paoli',
    'Laura Pausini',
    'Rita Pavone',
    'Eros Ramazzotti',
    'Vasco Rossi',
    'Luigi Tenco',
    'Roberto Vecchioni',
    'Antonello Venditti',
    'Alaine',
    'Buju Banton',
    'Pato Banton',
    'Burning Spear',
    'Jimmy Cliff',
    'Beres Hammond',
    'Toots Hibbert',
    'Barrington Levy',
    'Bob Marley',
    'Damian Marley',
    'Rita Marley',
    'Skip Marley',
    'Stephen Marley',
    'Ziggy Marley',
    'Sizzla',
    'Peter Tosh',
    'Joseph Attieh',
    'David M. Bailey',
    'Lydia Canaan',
    'IJK',
    'Sudirman Arshad',
    'Zee Avi',
    'Vince Chong',
    'M. Nasir',
    'P. Ramlee',
    'Shanon Shah',
    'Pete Teo',
    'Yuna',
    'Azmyl Yunor',
    'Meor Aziddin Yusof',
    'Alyah',
    'Walter Micallef',
    'Roberto Cantoral',
    'Óscar Chávez',
    'Lolita de la Colina',
    'Fernando Delgadillo',
    'Emmanuel',
    'Rubén Fuentes',
    'Ana Gabriel',
    'Juan Gabriel',
    'María Grever',
    'Saúl Hernández',
    'José Alfredo Jiménez',
    'Agustín Lara',
    'Armando Manzanero',
    'Carla Morrison',
    'Sofía Reyes',
    'Cuco Sánchez',
    'Joan Sebastian',
    'Marco Antonio Solís',
    'Aleks Syntek',
    'Lynda Thomas',
    'Consuelo Velázquez',
    'Julieta Venegas',
    'Pavel Stratan',
    'Stevie Ann',
    'Frank Boeijen',
    'Anneke van Giersbergen',
    'Marike Jager',
    'Laura Jansen',
    'Loona',
    'Lucky Fonz III',
    'Nielson',
    'Ntjam Rosie',
    'Ede Staal',
    'Anouk Teeuwe',
    'Herman van Veen',
    'Robert Westerholt',
    'Aaradhna',
    'Megan Alatini',
    'Robert Arnold',
    'Daniel Bedingfield',
    'Carly Binding',
    'Jackie Clarke',
    'Ashely Cooper',
    'Joe Cotton',
    'Annie Crummer',
    'Martin Curtis',
    'Lynette Diaz',
    'Dave Dobbyn',
    'Liam Finn',
    'Neil Finn',
    'Tim Finn',
    'Brooke Fraser',
    'Che Fu',
    'Rob Guest',
    'Luke Hurley',
    'Greg Johnson',
    'Phil Judd',
    'David Kilgour',
    'Nathan King',
    'Ladyhawke',
    'Shona Laing',
    'Lorde',
    'Ben Lummis',
    'Jamie McDell',
    'Fiona McDonald',
    'Anika Moa',
    'Howard Morrison',
    'Tex Morton',
    'John Rowles',
    'Bic Runga',
    'Boh Runga',
    'Hollie Smith',
    'Frankie Stevens',
    'Tiki Taane',
    'Marcus Turner',
    'Keith Urban',
    'Rosita Vai',
    'Hayley Westenra',
    'Annie Whittle',
    'Jahdiel',
    'Malcolm Guite',
    'Muma Gee',
    'Nneka',
    'Onyeka Onwenu',
    'Omawumi',
    'Tiwa Savage',
    'Aurora Aksnes',
    'Kari Bremnes',
    'Ane Brun',
    'Thomas Dybdahl',
    'Torgunn Flaten',
    'Magne Furuholmen',
    'Christine Guldbrandsen',
    'Morten Harket',
    'Monica Heldal',
    'Thom Hell',
    'William Hut',
    'Sissel Kyrkjebø',
    'Marit Larsen',
    'Sondre Lerche',
    'Espen Lind',
    'Magnet (born Even Johansen)',
    'Lene Marlin',
    'Maria Mena',
    'Silje Nergaard',
    'Janove Ottesen',
    'Robert Post',
    'Marion Ravn',
    'Kari Rueslåtten',
    'Iselin Solheim',
    'Susanne Sundfør',
    'Paul Waaktaar-Savoy',
    'Vegard Ylvisåker',
    'Bertine Zetlitz',
    'Lillebjørn Nilsen',
    'Siri Nilsen',
    'Joey Montana',
    'Chabuca Granda',
    'Gian Marco',
    'Pedro Suarez Vertiz',
    'Edyta Bartosiewicz',
    'Edyta Górniak',
    'Katy Carr',
    'Jacek Kaczmarski',
    'Kasia Moś',
    'Zeca Afonso',
    'Jorge Palma',
    'Sérgio Godinho',
    'David Fonseca',
    'Adriano Correia de Oliveira',
    'José Carlos Ary dos Santos',
    'JP Simões',
    'Fernando Tordo',
    'Vitorino',
    'Zayra Alvarez',
    'Tito Auger',
    'Puchi Balseiro',
    'Obie Bermúdez',
    'Americo Boschetti',
    'Lou Briel',
    'Roy Brown',
    'Antonio Cabán Vale',
    'Nano Cabrera',
    'Bobby Capó',
    'Vicente Carattini',
    'Santos Colón',
    'Elvis Crespo',
    'Tony Croatto',
    'Bobby Cruz',
    'Tite Curet Alonso',
    'Johnathan Dwayne',
    'Rafi Escudero',
    'Noel Estrada',
    'Farruko',
    'José Feliciano',
    'Luis Fonsi',
    'Kany García',
    'Gustavo Laureano',
    'Héctor Lavoe',
    'Ricky Martin',
    'Yolandita Monge',
    'Glenn Monroig',
    'Ednita Nazario',
    'Noelia',
    'José Nogueras',
    'Don Omar',
    'Angel "Cuco" Peña',
    'Ignacio Peña',
    'Carlos Ponce',
    'Sylvia Rexach',
    'Julito Rodriguez',
    'Dräco Rosa',
    'Zoraida Santiago',
    'Myrta Silva',
    'Olga Tañón',
    'Tommy Torres',
    'Juan Vélez',
    'Wilkins Vélez',
    'Yaire',
    'Daddy Yankee',
    'Zeny & Zory',
    'Michael Cretu',
    'Alexandra Stan',
    'Inna',
    'Delia Matache',
    'Veronika Dolina',
    'Yanka Dyagileva',
    'Alexander Gorodnitsky',
    'Lena Katina',
    'Eduard Khil',
    'Andrei Makarevich',
    'Sergey Nikitin',
    'Bulat Okudzhava',
    'Viktor Tsoi',
    'Yuri Vizbor',
    'Vladimir Vysotsky',
    'Celeste Buckingham',
    'Marika Gombitová',
    'Vašo Patejdl',
    'Dara Rolins',
    'Dežo Ursiny',
    'Koos du Plessis',
    'Jennifer Ferguson',
    'Anton Goosen',
    'Sonja Herholdt',
    'Steve Kekana',
    'Jim Neversink',
    'Verity Price',
    'Karen Zoid',
    'Lira (singer)',
    'Manuel Alejandro',
    'Pablo Alborán',
    'Luis Eduardo Aute',
    'María del Mar Bonet',
    'Miguel Bosé',
    'Nino Bravo',
    'Diego El Cigala',
    'Els Setze Jutges',
    'Manolo Garcia',
    'Paco Ibañez',
    'Enrique Iglesias',
    'Julio Iglesias',
    'Lluís Llach',
    'Victor Manuel',
    'Roger Mas',
    'Antonio Orozco',
    'Tomeu Penya',
    'José Luis Perales',
    'Porta',
    'Raimon',
    'Joaquín Sabina',
    'Joan Manuel Serrat',
    'Camilo Sesto',
    'Jaume Sisa',
    'Álex Ubago',
    'Desmond Kelly',
    'Nimal Mendis',
    'Clarence Wijewardena',
    'Mikael Åkerfeldt',
    'Fred Åkerström',
    'Ulla Andersson',
    'Tomas Andersson Wij',
    'AronChupa',
    'Kristofer Åström',
    'Lizzy DeVine',
    'Thomas Di Leva',
    'Nicolai Dunger',
    'Marie Fredriksson',
    'Per Gessle',
    'José González',
    'Nanne Grönvall',
    'Håkan Hellström',
    'Tommy Karevik',
    'Christian Kjellvander',
    'Laleh',
    'Jens Lekman',
    'Zara Larsson',
    'Lykke Li',
    'Lisa Miskovsky',
    'Stina Nordenstam',
    'Povel Ramel',
    'Robyn',
    'Ilya Salmanzadeh',
    'Stefan Sundström',
    'Evert Taube',
    'Isa Tengblad',
    'Anna Ternheim',
    'Joakim Thåström',
    'Cornelis Vreeswijk',
    'Lars Winnerbäck',
    'Sophie Zelmani',
    'Bastian Baker',
    'David Buzzi',
    'Simone Drexel',
    'Mélanie René',
    'Adele',
    'Lily Allen',
    'Ian Anderson',
    'Gabrielle Aplin',
    'Lauren Aquilina',
    'Joan Armatrading',
    'Rick Astley',
    'Kevin Ayers',
    'Gary Barlow',
    'Syd Barrett',
    'Rich Batsford',
    'James Bay',
    'Peter Bellamy',
    'Belouis Some',
    'Matt Bigland',
    'James Blunt',
    'David Bowie',
    'Robbie Boyd',
    'Billy Bragg',
    'Sarah Brightman',
    'Andy Brown',
    'Melanie Brown',
    'Kate Bush',
    'Euros Childs',
    'Melanie Chisholm',
    'Eric Clapton',
    'Dodie Clark',
    'Gary Clark',
    'Lloyd Cole',
    'JP Cooper',
    'Jessica Cornish',
    'Elvis Costello',
    'Beverley Craven',
    'Charlotte Gordon Cumming',
    'Gareth Davies',
    'Paul Stuart Davies',
    'Ray Davies',
    'Alex Day',
    'Sandy Denny',
    'Chris de Burgh',
    'Lynsey de Paul',
    'Marina Diamandis',
    'Dido',
    'Siobhán Donaghy',
    'Donovan',
    'Josh Doyle',
    'Nick Drake',
    'Duffy',
    'Ian Dury',
    'Emmy the Great',
    'Ella Eyre',
    'Marianne Faithfull',
    'Newton Faulkner',
    'Lena Fiagbe',
    'Kat Flint',
    'Ryan Fletcher',
    'Andi Fraggs',
    'Barry Gibb',
    'Maurice Gibb',
    'David Gilmour',
    'Ellie Goulding',
    'David Gray',
    'Alistair Griffin',
    'Malcolm Guite',
    'Noel Gallagher',
    'Ed Harcourt',
    'Nick Harper',
    'Roy Harper',
    'George Harrison',
    'PJ Harvey',
    'Justin Hayward',
    'Imogen Heap',
    'Paul Heaton',
    'Ella Henderson',
    'Ant Henson',
    'Boo Hewerdine',
    'Robyn Hitchcock',
    'Trevor Horn',
    'Ben Howard',
    'Jamelia',
    'Bert Jansch',
    'Elton John',
    'Tom Jones',
    'Wizz Jones',
    'Martyn Joseph',
    'Nik Kershaw',
    'Hani King',
    'Beverley Knight',
    'Steve Knightley',
    'Charlie Landsborough',
    'John Lennon',
    'Adam Leonard',
    'Al Lewis',
    'Leona Lewis',
    'Dua Lipa',
    'Cher Lloyd',
    'Jez Lowe',
    'Nick Lowe',
    'Ewan MacColl',
    'Kirsty MacColl',
    'Amy Macdonald',
    'Emily Maguire',
    'Zayn Malik',
    'Laura Marling',
    'Johnny Marr',
    'Michael Marra',
    'Steve Marriott',
    'John Martyn',
    'Brian May',
    'Conor Maynard',
    'Paul McCartney',
    'Shelagh McDonald',
    'Charlie McDonnell',
    'Rory McLeod',
    'Tom McRae',
    'Ralph McTell',
    'Mika',
    'Gary Moore',
    'James Morrison',
    'Morrissey',
    'Alexi Murdoch',
    'Graham Nash',
    'Anthony Newley',
    'John Newman',
    'Sheila Nicholls',
    'Heather Nova',
    'Ivor Novello',
    'Tom Odell',
    'Beth Orton',
    'Ozzy Osbourne',
    'Nerina Pallot',
    'Alex Parks',
    'Passenger',
    'Liam Payne',
    'Karen Poole',
    'Shelly Poole',
    'Mal Pope',
    'Paul Poulton',
    'Gerry Rafferty',
    'Ricky Ross',
    'Kate Rusby',
    'Emeli Sandé',
    'Polly Scattergood',
    'Ed Sheeran[1]',
    'Labi Siffre',
    'Lucie Silvas',
    'Robert Smith',
    'Sam Smith',
    'David Sneddon',
    'Yusuf Islam (formerly Cat Stevens)',
    'Al Stewart',
    'Joe Strummer',
    'Harry Styles',
    'Dave Swarbrick',
    'Roger Taylor',
    'Sandi Thom',
    'Richard Thompson',
    'Teddy Thompson',
    'Tanita Tikaram',
    'Steve Tilston',
    'Louis Tomlinson',
    'KT Tunstall',
    'Frank Turner',
    'Bonnie Tyler',
    'Bailey Tzuke',
    'Judie Tzuke',
    'Karl Wallinger',
    'Clifford T. Ward',
    'Shayne Ward',
    'Roger Waters',
    'Helen Watson',
    'Robbie Williams',
    'Robin Williamson',
    'Amy Winehouse',
    'Robert Wyatt',
    'Pete Wylie',
    'Sami Yusuf',
    'Mirla Castellanos',
    'Ilan Chester',
    'Guillermo Dávila',
    'Ricardo Montaner',
    'Jose Luis Rodriguez',
    'Aldemaro Romero',
    'Franco De Vita',
    'Tina Arena',
    'Sia',
    'Iggy Azalea',
    'John Butler',
    'Kasey Chambers',
    'Michael Hutchence',
    'Daniel Johns',
    'Jessica Mauboy',
    'Anne McCue',
    'Kylie Minogue',
    'Bon Scott',
    'Guy Sebastian',
    'Cody Simpson',
    'Rob Swire',
    'Angus and Julia Stone',
    'Dino Merlin',
    'Bryan Adams',
    'Melissa Auf der Maur',
    'Justin Bieber',
    'Matthew Good',
    'Alexz Johnson',
    'Daniel Lanois',
    'James LaBrie',
    'Geddy Lee',
    'Gordon Lightfoot',
    'Shawn Mendes',
    'Alanis Morissette',
    'Alannah Myles',
    'Carl Newman',
    'Aldo Nova',
    'Robbie Robertson',
    'Buffy Sainte-Marie',
    'Skye Sweetnam',
    'David Usher',
    'Neil Young',
    'Tom Araya',
    'Darko Rundek',
    'Zlatan Stipišić Gibonni',
    'Branimir Štulić',
    'Jouni Hynynen',
    'Jyrki 69',
    'Andy McCoy',
    'Timo Rautiainen',
    'Gösta Sundqvist',
    'Timo Tolkki',
    'Ville Valo',
    'Toni Wirtanen',
    'Lauri Ylonen',
    'Bernard Bonvoisin',
    'Étienne Daho',
    'Zazie',
    'Udo Dirkschneider',
    'Max Koffler',
    'Klaus Meine',
    'Hong Kong',
    'George Lam',
    'Bjork',
    'Babbu Maan',
    'A. R. Rahman',
    'Bono',
    'Enya',
    'Órla Fallon',
    'Lynn Hilary',
    'Niall Horan',
    'Zucchero',
    'Japan',
    'Aimer',
    'Mao Abe',
    'Aiko',
    'Angela Aki',
    'Yūko Andō',
    'Chara',
    'Cocco',
    'CooRie',
    'Joe Inoue',
    'Kurumi Enomoto',
    'Masaharu Fukuyama',
    'Gackt',
    'Ayumi Hamasaki',
    'Motohiro Hata',
    'Megumi Hinata',
    'Ken Hirai',
    'Mayumi Horikawa',
    'Hyde',
    'Leo Ieiri',
    'Mari Iijima',
    'Koshi Inaba',
    'Yōsui Inoue',
    'Shigeru Izumiya',
    'Ai Kawashima',
    'Hiroshi Kitadani',
    'Kokia',
    'Kotringo',
    'Koda Kumi',
    'Mai Kuraki',
    'Keisuke Kuwata',
    'Olivia Lufkin',
    'Noriyuki Makihara',
    'Yumi Matsutoya',
    'Miwa',
    'Yui Mizuno',
    'Showtaro Morikubo',
    'Miyuki Nakajima',
    'Yuto Nakajima',
    'Uri Nakayama',
    'Sakurako Ohara',
    'Tamio Okuda',
    'Chihiro Onitsuka',
    'Ai Otsuka',
    'Yuki Saito',
    'Maaya Sakamoto',
    'Jun Shibata',
    'Ringo Shiina',
    'Akiko Shikata',
    'SoulJa',
    'Shikao Suga',
    'Yuya Takaki',
    'Yukihide Takekawa',
    'Mariya Takeuchi',
    'Hikaru Utada',
    'Hitomi Yaida',
    'Etsuko Yakushimaru',
    'Maria Yamamoto',
    'Tatsuro Yamashita',
    'Takuro Yoshida',
    'Yui',
    'Yuna',
    'Liam Finn',
    'Neil Finn',
    'Tim Finn',
    'Lorde',
    'Jamie McDell',
    'Bic Runga',
    'Hollie Smith',
    'Stan Walker',
    'Hayley Westenra',
    'Muma Gee',
    'Niyola',
    'Waje',
    'Salman Ahmad',
    'Ali Azmat',
    'Zeek Afridi',
    'Humaira Arshad',
    'Atif Aslam',
    'Iqbal Bano',
    'Haroon',
    'Mehdi Hassan',
    'Ahmed Jahanzeb',
    'Ustad Nusrat Fateh Ali Khan',
    'Ali Zafar',
    'Dong Abay',
    'Freddie Aguilar',
    'Ogie Alcasid',
    'Cynthia Alexander',
    'Barbie Almalbis',
    'Joey Ayala',
    'Christian Bautista',
    'Rico Blanco',
    'Ely Buendia',
    'Jose Mari Chan',
    'Charice (Jake Zyrus)',
    'Yeng Constantino',
    'Billy Joe Crawford',
    'Sharon Cuneta',
    'Jay Durias',
    'Eraserheads',
    'Pops Fernandez',
    'Sarah Geronimo',
    'Janno Gibbs',
    'Rachelle Ann Go',
    'Kyla',
    'Bamboo Mañalac',
    'Maine Mendoza',
    'Chito Miranda',
    'Kitchie Nadal',
    'Martin Nievera',
    'Nina',
    'Kylie Padilla',
    'Gary Valenciano',
    'Princess Velasco',
    'Regine Velasquez',
    'Yael Yuzon',
    'Alexandra Stan',
    'Momčilo Bajagić',
    'Đorđe Balašević',
    'Zvonko Bogdan',
    'Dejan Cukić',
    'Nikola Čuturilo',
    'Vlada Divljan',
    'Bebi Dol',
    'Bora Đorđević',
    'Zvonimir Đukić Đule',
    'Bane Krstić',
    'Kiki Lesendrić',
    'Srđan Marjanović',
    'Slađana Milošević',
    'Milan Mladenović',
    'Ljuba Ninković',
    'Madame Piano',
    'Ana Popović',
    'Toma Zdravković',
    'Predrag Živković Tozovac',
    'Cristina Boshoff',
    'Johnny Clegg',
    'Anton Goosen',
    'David Kramer',
    'Karen Zoid',
    'Ailee',
    'Bang Yongguk',
    'BoA',
    'BTS (Bangtan Boys)',
    'Cho Yong-pil',
    'G-Dragon',
    'Im Chang-jung',
    'IU',
    'J-Hope',
    'Jun Jinyoung',
    'Jung Yonghwa',
    'Kang Seungyoon',
    'Kangta',
    'Kim C',
    'Kim Dong-ryool',
    'Moon Hee-jun',
    'Kim Jong-seo',
    'Kim Kwang-Seok',
    'Kim Jaejoong',
    'Kim Jonghyun',
    'Kim Junsu',
    'Kim Sa-rang',
    'Lee Jonghyun',
    'Lee Juck',
    'LE',
    'MC Sniper',
    'The One',
    'Park Hyo-shin',
    'Park Jin-young',
    'Psy',
    'Rain',
    'RM',
    'Seo Taiji',
    'Shin Hae Chul',
    'Shin Seung Hun',
    'Suga',
    'Tablo',
    'Wheesung',
    'Park Yeeun',
    'Yoon Jong-shin',
    'Yoo Hee-Yeol',
    'Caroline Hjelt',
    'Aino Jawo',
    'Tove Lo',
    'Chang Yu-sheng',
    'Chang Chen-yue',
    'Lala Hsu',
    'Enno Cheng',
    'Cheer Chen',
    'David Tao',
    'Evan Yo',
    'Jay Chou',
    'Kenji Wu',
    'Deserts Chang',
    'Leehom Wang',
    'Jolin Tsai',
    'Tank',
    'Will Pan',
    'Sezen Aksu',
    'Mazhar Alanson',
    'Kenan Doğulu',
    'Onur Özsu',
    'Orhan Gencebay',
    'İlhan İrem',
    'Kayahan',
    'Barış Manço',
    'Bülent Ortaçgil',
    'Nazan Öncel',
    'Münir Nurettin Selçuk',
    'Tarkan',
    'Yıldız Tilbe',
    'Natalie Gioia',
    'Adele',
    'Sade Adu',
    'Damon Albarn',
    'Marc Almond',
    'Ian Anderson',
    'Jon Anderson',
    'Badly Drawn Boy (Damon Gough)',
    'Gary Barlow',
    'Syd Barrett',
    'Julian Barry',
    'Blaze Bayley',
    'Natasha Bedingfield',
    'Nick Beggs',
    'Adrian Belew',
    'Amelle Berrabah',
    'James Blunt',
    'Betty Boo',
    'David Bowie',
    'Sarah Brightman',
    'Keisha Buchanan',
    'Mutya Buena',
    'Jake Bugg',
    'Kate Bush',
    'Biff Byford',
    'Katy Carr',
    'Eric Clapton',
    'Phil Collins',
    'Tulisa Contostavlos',
    'Elvis Costello',
    'David Coverdale',
    'Charlotte Gordon Cumming',
    'Dappy',
    'Ray Davies',
    'Cathy Dennis',
    'Marina Lambrini Diamandis',
    'Paul Di\'Anno',
    'Bruce Dickinson',
    'Pete Doherty',
    'Donovan',
    'Stephen Duffy',
    'Joe Elliott',
    'Marianne Faithfull',
    'Peter Gabriel',
    'Liam Gallagher',
    'Noel Gallagher',
    'Barry Gibb',
    'Maurice Gibb',
    'Robin Gibb',
    'Ian Gillan',
    'David Gilmour',
    'Gary Glitter',
    'Ellie Goulding',
    'David Gray',
    'Matt Hales',
    'Rob Halford',
    'Pete Ham',
    'Peter Hammill',
    'Calvin Harris',
    'George Harrison',
    'Justin Hawkins',
    'Imogen Heap',
    'Mick Hucknall',
    'Ian Hunter',
    'Jessie J',
    'Joe Jackson',
    'Mick Jagger',
    'Jem',
    'Elton John',
    'Brian Johnson',
    'Matt Johnson',
    'Mick Jones',
    'Nik Kershaw',
    'Jim King',
    'David Knopfler',
    'Mark Knopfler',
    'Greg Lake',
    'Simon Le Bon',
    'Lemmy',
    'John Lennon',
    'Leona Lewis',
    'Gary Lightbody',
    'Limahl',
    'Cher Lloyd',
    'Nick Lowe',
    'Jeff Lynne',
    'Paddy McAloon',
    'Paul McCartney',
    'Christine McVie',
    'Shirley Manson',
    'Zayn Malik',
    'Steve Marriott',
    'Brian May',
    'Freddie Mercury',
    'George Michael',
    'Morrissey',
    'Kate Nash',
    'John Newman',
    'Jim Noir',
    'Richard O\'Brien',
    'Rita Ora',
    'John Otway',
    'Bill Owen',
    'Mark Owen',
    'Ozzy Osbourne',
    'John Payne',
    'Liam Payne',
    'Robert Plant',
    'Plunkett',
    'Heidi Range',
    'Keith Relf',
    'Tim Rice',
    'Keith Richards',
    'Gavin Rossdale',
    'Graham Russell',
    'Emeli Sandé',
    'Sam Smith',
    'Ringo Starr',
    'Al Stewart',
    'Rod Stewart',
    'Sting',
    'Joss Stone',
    'Joe Strummer',
    'Harry Styles',
    'Jeremy Taylor',
    'Roger Taylor',
    'David Tibet',
    'Louis Tomlinson',
    'Alex Turner',
    'Tom Vek',
    'Roger Waters',
    'Florence Welch',
    'Paul Weller',
    'John Wetton',
    'Kim Wilde',
    'Roy Wood',
    'Richard Wright',
    'Thom Yorke',
    'Will Young',
    '50 Cent',
    'Ryan Adams',
    'Christina Aguilera',
    'Priscilla Ahn',
    'Ray Alder',
    'Nadia Ali',
    'Gregg Allman',
    'Dave Alvin',
    'Trey Anastasio',
    'Ken Andrews',
    'Michael Andrews',
    'John Arch',
    'David Archuleta',
    'Billie Joe Armstrong',
    'Louis Armstrong',
    'Dan Auerbach',
    'Francesca Battistelli',
    'Beck',
    'Walter Becker',
    'Joey Belladonna',
    'Chuck Berry',
    'Dickey Betts',
    'Beyoncé',
    'Larry Blackmon',
    'Karl Blau',
    'Michael Bolton',
    'Jon Bon Jovi',
    'Olivia Bonilla',
    'Ralston Bowles',
    'Brandon Boyd',
    'D. S. Bradford',
    'Colin Brooks',
    'Garth Brooks',
    'Lindsey Buckingham',
    'Benjamin Burnley',
    'Glen Burtnik',
    'John Bush',
    'Paul Butterfield',
    'Sarah Buxton',
    'David Byrne',
    'Ryan Cabrera',
    'Jerry Cantrell',
    'Mariah Carey',
    'Eric Carmen',
    'Chris Carrabba',
    'Peter Cetera',
    'Tracy Chapman',
    'Gary Cherone',
    'Peter Cincotti',
    'Kelly Clarkson',
    'Roger Clyne',
    'Kurt Cobain',
    'Fred Cole',
    'Lisa Coleman',
    'Billy Corgan',
    'Chris Cornell',
    'Jonathan Coulton',
    'Robert Cray',
    'Peter Criss',
    'Kevin Cronin',
    'David Crosby',
    'Sheryl Crow',
    'Rivers Cuomo',
    'John Curulewski',
    'Miley Cyrus',
    'Terence Trent D\'Arby',
    'Jonathan Davis',
    'Howie Day',
    'Tom DeLonge',
    'Dennis DeYoung',
    'Neil Diamond',
    'Bo Diddley',
    'Ronnie James Dio',
    'Willie Dixon',
    'Don Dokken',
    'David Draiman',
    'Haylie Duff',
    'Hilary Duff',
    'Sean Duffy',
    'Bob Dylan',
    'Jakob Dylan',
    'Danny Elfman',
    'Eminem',
    'Ace Enders',
    'Gloria Estefan',
    'Donald Fagen',
    'Don Felder',
    'Fergie',
    'William Fitzsimmons',
    'John Flansburgh',
    'Brandon Flowers',
    'John Fogerty',
    'Ben Folds',
    'John Frusciante',
    'Ace Frehley',
    'Glenn Frey',
    'Vic Fuentes',
    'Becky G',
    'David Gates',
    'Gloria Gaynor',
    'Benjamin Gibbard',
    'Billy Gibbons',
    'Eliza Gilkyson',
    'Selena Gomez',
    'Ariana Grande',
    'Hank Green',
    'Christina Grimmie',
    'Dave Grohl',
    'Buddy Guy',
    'Sammy Hagar',
    'Daryl Hall',
    'Jessica Harp',
    'Ben Harper',
    'Deborah Harry',
    'Sophie B. Hawkins',
    'Angel Haze',
    'Mark Heard',
    'Levon Helm',
    'Logan Henderson',
    'Jimi Hendrix',
    'Don Henley',
    'James Hetfield',
    'Buddy Holly',
    'Mark Hoppus',
    'Robert Hunter',
    'Alan Jackson',
    'Janet Jackson',
    'Michael Jackson',
    'Jay-Z',
    'Stephan Jenkins',
    'Robert Johnson',
    'JoJo',
    'Joe Jonas',
    'Kevin Jonas',
    'Nick Jonas',
    'Rickie Lee Jones',
    'Janis Joplin',
    'Tyler Joseph',
    'Maynard James Keenan',
    'R. Kelly',
    'Mean Gene Kelton',
    'Eddie Kendricks',
    'Kenna',
    'Doug Kershaw',
    'Kesha',
    'Alicia Keys',
    'Anthony Kiedis',
    'Bobby Kimball',
    'B.B. King',
    'Beyoncé Knowles',
    'Lady Gaga',
    'Mark Lanegan',
    'Adam Lambert',
    'Ray LaMontagne',
    'Cyndi Lauper',
    'Bernie Leadon',
    'Bethany Joy Lenz',
    'Jared Leto',
    'Adam Levine',
    'Aaron Lewis',
    'Philip Lindholm',
    'Lisa Loeb',
    'Kenny Loggins',
    'Lindsay Lohan',
    'Jennifer Lopez',
    'Joe Lopez',
    'Demi Lovato',
    'Courtney Love',
    'Lyle Lovett',
    'John Linnell',
    'Ross Lynch',
    'Loretta Lynn',
    'Benji Madden',
    'Joel Madden',
    'Madonna',
    'Kaitlyn Maher',
    'Jeff Mangum',
    'Barry Manilow',
    'Aimee Mann',
    'Marilyn Manson',
    'Marce',
    'Chan Marshall',
    'Richard Marx',
    'James Maslow',
    'Matchstik',
    'Dave Matthews',
    'Anthony Marinelli',
    'John Mayer',
    'Natalie Merchant',
    'Edwin McCain',
    'Jesse McCartney',
    'Michael McDonald',
    'Jon McLaughlin',
    'Katharine McPhee',
    'Travis Meeks',
    'Randy Meisner',
    'John Mellencamp',
    'Wendy Melvoin',
    'Stephin Merritt',
    'AJ Michalka',
    'Aly Michalka',
    'Rhett Miller',
    'Roger Miller',
    'Steve Miller',
    'Nicki Minaj',
    'Freddy Moore',
    'Jim Morrison',
    'Chuck Mosley',
    'Elliott Murphy',
    'Dave Mustaine',
    'Frank J. Myers',
    'Faheem Najm',
    'Nelly',
    'Dan Nelson',
    'Michael Nesmith',
    'Mike Ness',
    'Randy Newman',
    'Ne-Yo',
    'Stevie Nicks',
    'Keri Noble',
    'The Notorious B.I.G.',
    'Justin Nozuka',
    'Ted Nugent',
    'John Oates',
    'Ric Ocasek',
    'Roy Orbison',
    'Joan Osborne',
    'Buck Owens',
    'David Paich',
    'Mike Patton',
    'Carlos Pena, Jr.',
    'CeCe Peniston',
    'Christina Perri',
    'Sarah Perrotta',
    'Katy Perry',
    'Linda Perry',
    'Steve Perry',
    'Tom Petty',
    'Glen Phillips',
    'Dave Pirner',
    'Pink',
    'Rachel Platten',
    'Jimmy Pop',
    'John Popper',
    'Grace Potter',
    'Prince',
    'Eddie Rabbitt',
    'Rakim',
    'Twiggy Ramirez',
    'Redfoo',
    'Bebe Rexha',
    'Trent Reznor',
    'Lionel Richie',
    'Johnny Rivers',
    'Smokey Robinson',
    'Zack de la Rocha',
    'Sixto Rodriguez',
    'Kenny Rogers',
    'Ed Roland',
    'Axl Rose',
    'David Lee Roth',
    'Todd Rundgren',
    'Leon Russell',
    'John Rzeznik',
    'Kendall Schmidt',
    'Timothy B. Schmit',
    'Big Sean',
    'Drew Seeley',
    'Bob Seger',
    'Selena',
    'Adam Selzer',
    'Tommy Shaw',
    'Adam Shearer',
    'Duncan Sheik',
    'Shwayze',
    'Gene Simmons',
    'Paul Simon',
    'Ashlee Simpson',
    'Helen Slater',
    'Kathy Sledge',
    'Michael W. Smith',
    'Dee Snider',
    'J.D. Souther',
    'Britney Spears',
    'Bruce Springsteen',
    'Layne Staley',
    'Paul Stanley',
    'Scott Stapp',
    'Jeffree Star',
    'Gwen Stefani',
    'Stephen Stills',
    'Barbra Streisand',
    'Bruce Sudano',
    'Donna Summer',
    'Gene Summers',
    'Matthew Sweet',
    'Michael Sweet',
    'Taylor Swift',
    'James Taylor',
    'Courtney Taylor-Taylor',
    'Rob Thomas',
    'Justin Timberlake',
    'Ashley Tisdale',
    'Mark Tornillo',
    'Meghan Trainor',
    'Roger Troutman',
    'Joe Lynn Turner',
    'Jeff Tweedy',
    'Conway Twitty',
    'Steven Tyler',
    'Carrie Underwood',
    'Eddie Vedder',
    'Kate Voegele',
    'Tom Waits',
    'Joe Walsh',
    'Crystal Waters',
    'Kanye West',
    'Paul Westerberg',
    'Brooke White',
    'Jack White',
    'Maurice White',
    'will.i.am',
    'Hayley Williams',
    'Joseph Williams',
    'Paul Williams',
    'Ann Wilson',
    'Brian Wilson',
    'Nancy Wilson',
    'Kip Winger',
    'Stevie Wonder',
    '"Weird Al" Yankovic',
    'Doug Yoel',
    'James Young',
    'Steven Van Zandt',
    'Donnie Van Zant',
    'Johnny Van Zant',
    'Ronnie Van Zant',
    'Frank Zappa',
    'Zendaya',
    'Rob Zombie',
    'Pablo Sciuto',
    'Ilan Chester',
    'Guillermo Dávila',
    'Aldemaro Romero',
    'Franco De Vita',
    'Sơn Tùng M-TP',
    'Michael Jones',
    "Catie Curtis",
    "Billy Ray Cyrus",
    "Vernon Dalhart",
    "Sean Danielsen",
    "Glenn Danzig",
    "Gail Davies",
    "Kimya Dawson",
    "Grey DeLisle",
    "Kris Delmhorst",
    "Lana Del Rey",
    "Rebekah Del Rio",
    "Iris DeMent",
    "Rick DePiro",
    "Jason Derulo",
    "John Denver",
    "Ani DiFranco",
    "Maria D'Luz",
    "Mike Doughty",
    "Gregory Douglass",
    "Connie Dover",
    "The-Dream",
    "Marshall Drew",
    "DW (Dave) Drouillard",
    "Bob Dylan",
    "Kate Earl",
    "Stacey Earle",
    "Justin Townes Earle",
    "Steve Earle",
    "Kenneth \"Babyface\" Edmonds",
    "Jonathan Edwards",
    "Mark Erelli",
    "Alejandro Escovedo",
    "Carmen Espinoza-Rodriquez",
    "Melissa Etheridge",
    "Richard Fariña",
    "Melissa Ferrick",
    "Roberta Flack",
    "Dan Fogelberg",
    "John Fogerty",
    "Ben Folds",
    "Keith Follesé",
    "Steve Forbert",
    "Jon Foreman",
    "Ruthie Foster",
    "Jeffrey Foucault",
    "Michael Fracasso",
    "Black Francis",
    "Jackson C. Frank",
    "Bob Franke",
    "Carole Fredericks",
    "Dean Friedman",
    "Lefty Frizzell",
    "Annie Gallup",
    "Mary Gauthier",
    "Marvin Gaye",
    "Teddy Geiger",
    "Natalie Gelman",
    "Daughn Gibson",
    "Vance Gilbert",
    "Vince Gill",
    "Lotti Golden",
    "Steve Goodman",
    "Selena Gomez",
    "Lesley Gore",
    "John Gorka",
    "Nick Granato",
    "Ariana Grande",
    "Jackie Greene",
    "Patty Griffin",
    "Nanci Griffith",
    "Arlo Guthrie",
    "Sarah Lee Guthrie",
    "Woody Guthrie",
    "Gwendolyn",
    "Merle Haggard",
    "Tom T. Hall",
    "Halsey",
    "Kristy Hanson",
    "Tim Hardin",
    "Jack Hardy",
    "Ben Harper",
    "Ciara Harris",
    "Emmylou Harris",
    "Jesse Harris",
    "Debbie Harry",
    "Beth Hart",
    "John Hartford",
    "Juliana Hatfield",
    "Richie Havens",
    "Ted Hawkins",
    "Hunter Hayes",
    "Jimi Hendrix",
    "Terri Hendrix",
    "Don Henley",
    "Ari Hest",
    "James Hetfield",
    "John Hiatt",
    "Sara Hickman",
    "Utada Hikaru",
    "Lauryn Hill",
    "Chris Hillman",
    "Anne Hills",
    "Keri Hilson",
    "Tyler Hilton",
    "Tish Hinojosa",
    "Will Hoge",
    "J. Holiday",
    "Cisco Houston",
    "Whitney Houston",
    "Bob Howard",
    "Grayson Hugh",
    "Tim Hughes",
    "Meg Hutchinson",
    "Walter Hyatt",
    "Janis Ian",
    "India.Arie",
    "Jim Infantino",
    "David Ippolito",
    "Allison Iraheta",
    "Iron & Wine",
    "Chris Isaak",
    "Gregory Alan Isakov",
    "Bon Iver",
    "Carl Jackson",
    "Janet Jackson",
    "Jermaine Jackson",
    "Michael Jackson",
    "Avi Jacob",
    "Nicky Jam",
    "Brendan James",
    "Sarah Jarosz",
    "Jaymay",
    "Nikki Jean",
    "Stephan Jenkins",
    "Waylon Jennings",
    "Molly Jenson",
    "Jewel",
    "Eilen Jewell",
    "Kari Jobe",
    "Billy Joel",
    "Jack Johnson",
    "Jamey Johnson",
    "Freedy Johnston",
    "Norah Jones",
    "Sharon Jones",
    "Montell Jordan",
    "Simon Joyner",
    "Gary Jules",
    "Tyler Joseph",
    "Si Kahn",
    "Kieran Kane",
    "Lucy Kaplansky",
    "Kashif",
    "Mat Kearney",
    "Robert Earl Keen",
    "Toby Keith",
    "Kelis",
    "Malcolm David Kelley",
    "R. Kelly",
    "Tori Kelly",
    "Alicia Keys",
    "Yoko Kikuchi",
    "Carole King",
    "Charles E. King",
    "Claude King",
    "Elle King",
    "Sonya Kitchell",
    "Charles Michael Kittridge",
    "Hayley Kiyoko",
    "\"Spider\" John Koerner",
    "Nikhil Korula",
    "Mark Kozelek",
    "Alison Krauss",
    "Kris Kristofferson",
    "Lenny Kravitz",
    "Ben Kweller",
    "Jimmy LaFave",
    "Miranda Lambert",
    "Ray LaMontagne",
    "Patty Larkin",
    "Jim Lauderdale",
    "Christine Lavin",
    "Scott Law",
    "Lead Belly",
    "Amos Lee",
    "Amy Lee",
    "Tom Lehrer",
    "Bethany Joy Lenz",
    "David Levin",
    "Blake Lewis",
    "Bob Lind",
    "Lisa Loeb",
    "Jennifer Lopez",
    "Demi Lovato",
    "Laura Love",
    "Karen Lovely",
    "Lyle Lovett",
    "Lera Lynn",
    "Rod MacDonald",
    "Dougie MacLean",
    "Bill Madden",
    "Martie Maguire",
    "Taj Mahal",
    "Sananda Maitreya",
    "David Mallett",
    "Michelle Malone",
    "Melissa Manchester",
    "Barry Mann",
    "Teena Marie",
    "Bruno Mars",
    "Bob Martin",
    "Melanie Martinez",
    "Dana Mase",
    "Michael Masser",
    "Kathy Mattea",
    "Nanette Maxine",
    "John Mayer",
    "Curtis Mayfield",
    "Jennette McCurdy",
    "Country Joe McDonald",
    "Reba McEntire",
    "Tim McGraw",
    "Roger McGuinn",
    "Nellie McKay",
    "Bonnie McKee",
    "Lori McKenna",
    "Erin McKeown",
    "Rod McKuen",
    "Don McLean",
    "James McMurtry",
    "Melanie",
    "Bridgit Mendler",
    "Idina Menzel",
    "Michael J. Merenda, Jr.",
    "Tift Merritt",
    "Pia Mia",
    "Julia Michaels",
    "Ingrid Michaelson",
    "Julie Miller",
    "Lin-Manuel Miranda",
    "Anais Mitchell",
    "Keb' Mo'",
    "Moby",
    "Janelle Monáe",
    "Ben Moody",
    "Mandy Moore",
    "Allison Moorer",
    "Bill Morrissey",
    "Jason Mraz",
    "Shawn Mullins",
    "Peter Mulvey",
    "Jimmy Murphy",
    "Michael Martin Murphey",
    "Kacey Musgraves",
    "Anna Nalick",
    "Leigh Nash",
    "Nina Nastasia",
    "Matt Nathanson",
    "Holly Near",
    "Fred Neil",
    "Willie Nelson",
    "Jennifer Nettles",
    "Mickey Newbury",
    "Carrie Newcomer",
    "Randy Newman",
    "Joanna Newsom",
    "Stevie Nicks",
    "Britt Nicole",
    "Willie Nile",
    "Harry Nilsson",
    "Keri Noble",
    "Dianne Nola",
    "The Notorious B.I.G.",
    "Bradley Nowell",
    "Laura Nyro",
    "Conor Oberst",
    "Tim O'Brien",
    "Phil Ochs",
    "Maura O'Connell",
    "Aoife O'Donovan",
    "Will Oldham",
    "Tony Oller",
    "David Olney",
    "Kristina Olsen",
    "Johnny Otis",
    "Jim Page",
    "Brad Paisley",
    "Dana Parish",
    "Dolly Parton",
    "Ellis Paul",
    "Tom Paxton",
    "Johnny Paycheck",
    "Herb Pedersen",
    "Sarah Pedinotti",
    "Yolanda Pérez",
    "Pierce Pettis",
    "Madeleine Peyroux",
    "Liz Phair",
    "Kelly Joe Phelps",
    "Grant-Lee Phillips",
    "Sam Phillips",
    "Shawn Phillips",
    "Utah Phillips",
    "Rod Picott",
    "Pitbull",
    "Gene Pitney",
    "Doc Pomus",
    "Cassadee Pope",
    "Catherine Porter",
    "Willy Porter",
    "Grace Potter",
    "Elvis Presley",
    "Tristan Prettyman",
    "Dory Previn",
    "Toni Price",
    "Prince",
    "John Prine",
    "Top Quality",
    "Joshua Radin",
    "Bonnie Raitt",
    "Tony Ramey",
    "Willis Alan Ramsey",
    "Carmino Ravosa",
    "Otis Redding",
    "Ann Reed",
    "Lou Reed",
    "Bebe Rexha",
    "Trent Reznor",
    "Kim Richey",
    "Jonathan Richman",
    "Amy Rigby",
    "Rihanna",
    "Josh Ritter",
    "Carson Robison",
    "Zack de la Rocha",
    "Jimmie Rodgers",
    "Henry Rollins",
    "Dräco Rosa",
    "Raina Rose",
    "Emmy Rossum",
    "Josh Rouse",
    "David Rovics",
    "Peter Rowan",
    "Darius Rucker",
    "Tom Rush",
    "Tom Russell",
    "Rachael Sage",
    "Doug Sahm",
    "Richie Sambora",
    "Martha Scanlan",
    "Marc Scibilia",
    "Darrell Scott",
    "John Sebastian",
    "Pebe Sebert",
    "Neil Sedaka",
    "Pete Seeger",
    "Martin Sexton",
    "Tupac Shakur",
    "Maia Sharp",
    "Billy Joe Shaver",
    "Jules Shear",
    "Duncan Sheik",
    "Blake Shelton",
    "Vonda Shepard",
    "Richard Shindell",
    "Michelle Shocked",
    "Paul Siebel",
    "Carly Simon",
    "Paul Simon",
    "Sisqó",
    "Ricky Skaggs",
    "Patrick Sky",
    "Megan Slankard",
    "P. F. Sloan",
    "Darden Smith",
    "Elliott Smith",
    "Michael Smith",
    "Patti Smith",
    "Chris Smither",
    "Todd Snider",
    "Jill Sobule",
    "Ben Sollee",
    "Trey Songz",
    "Jo-El Sonnier",
    "Soraya",
    "Regina Spektor",
    "Aaron Sprinkle",
    "Bill Staines",
    "Chris Stapleton",
    "David Steinhart",
    "Colin Stetson",
    "Sufjan Stevens",
    "John Stewart",
    "Wynn Stewart",
    "Stephen Stills",
    "Marty Stuart",
    "Patrick Stump",
    "Alison Sudol",
    "Gene Summers",
    "Taylor Swift",
    "Raven-Symoné",
    "Corey Taylor",
    "Eric Taylor",
    "James Taylor",
    "Livingston Taylor",
    "Louise Taylor",
    "Ryan Tedder",
    "Jack Tempchin",
    "Chloe Temtchine",
    "Vienna Teng",
    "Chris Thile",
    "Robin Thicke",
    "Justin Timberlake",
    "Rob Thomas",
    "Gone Thursday",
    "Chris Tomlin",
    "Meghan Trainor",
    "Steven Tyler",
    "Usher",
    "Grace VanderWaal",
    "Guy Van Duser",
    "Dave Van Ronk",
    "Townes Van Zandt",
    "Phil Vassar",
    "Vassy",
    "Stoll Vaughan",
    "Suzanne Vega",
    "Laura Veirs",
    "Justin Vernon",
    "John Vesely",
    "Jack Vidgen",
    "Rhonda Vincent",
    "Eric Von Schmidt",
    "Loudon Wainwright III",
    "Sloan Wainwright",
    "Tom Waits",
    "Butch Walker",
    "Jerry Jeff Walker",
    "M. Ward",
    "Linda Waterfall",
    "Doc Watson",
    "Lil Wayne",
    "Gillian Welch",
    "Kevin Welch",
    "Susan Werner",
    "Matt Wertz",
    "Cheryl Wheeler",
    "Erica Wheeler",
    "Brooke White",
    "Jack White",
    "Josh White",
    "Maurice White",
    "Chris Whitley",
    "David Wilcox",
    "Brooks Williams",
    "Dar Williams",
    "Don Williams",
    "Geoffrey Williams",
    "Hank Williams",
    "Hank Williams Jr.",
    "Keller Williams",
    "Lucinda Williams",
    "Pharrell Williams",
    "Victoria Williams",
    "Cris Williamson",
    "Gretchen Wilson",
    "Jesse Winchester",
    "Cody Wise",
    "Bill Withers",
    "Denison Witmer",
    "Jim Wolf",
    "Kate Wolf",
    "Bobby Womack",
    "Juliet Wyers",
    "Rachael Yamagata",
    "Dwight Yoakam",
    "Jesse Colin Young",
    "Steve Young",
    "Frank Zappa",
    "Mirah Yom Tov Zeitlyn",
    "Warren Zevon",
    "Natalia Zukerman"
    'Matthew Tuck'
]